name: Deploy EKS Cluster

on:
  # Get AWS Keys input to run the action
  workflow_dispatch:
    inputs:
      AccessKey:
        description: AWS Access Key
        required: true
      SecretKey:
        description: AWS Secret Key
        required: true

jobs:
  
  build:
    # Run on ubuntu latest
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout the github repo
      - uses: actions/checkout@v4

      - name: Update the apt repo and install aws cli
        run: | 
          apt update && apt install curl unzip -y
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
          unzip awscliv2.zip 
          ./aws/install 

      # Run the shell script to perform all the actitivies
      - name: Run a one-line script
        env:
          AWS_ACCESS_KEY_ID: ${{ github.event.inputs.AccessKey }}
          AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.SecretKey }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: bash start.sh
